# Generated by Django 3.1.5 on 2021-01-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='vendor_uploads/')),
                ('uploaded_date', models.DateTimeField(auto_now=True, verbose_name='Date Uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tx_date', models.DateField(null=True)),
            ],
        ),
    ]
